### ISSUE TITLE
[Bug] Asking Siri to change temperature results in nothing happening

### ISSUE THREAD

**Issue by ghost** [benov84/homebridge-eldom-heater#1]
Asking Siri to change the temperature does nothing. Changing temperature in Home app works.

How to replicate:
1. Ask Siri to set temperature to specific value “Siri, set heater to 21 degrees”
2. Nothing happens

Running iOS 17

**Comment by benov84** [comment]
This is not related to the homebridge plugin! Although it is working on my setup, so the problem is on your side.
Check the naming of your heater device.

**Comment by ghost** [comment]
> This is not related to the homebridge plugin! Although it is working on my setup, so the problem is on your side. Check the naming of your heater device.

Unfortunately, I left a part out. 
When Siri is tasked with changing the temperature, it says “OK, heating to 20°C.”. Theres only one heater. Maybe it’s a model issue? Do you want me to send some logs and more details? If it’s not working correctly it’s related to your plugin.

**Comment by benov84** [comment]
> > This is not related to the homebridge plugin! Although it is working on my setup, so the problem is on your side. Check the naming of your heater device.
> 
> 
> 
> Unfortunately, I left a part out. 
> 
> When Siri is tasked with changing the temperature, it says “OK, heating to 20°C.”. Theres only one heater. Maybe it’s a model issue? Do you want me to send some logs and more details? If it’s not working correctly it’s related to your plugin.
> 
> 

I can control the heater using Siri. As I said, this can't be issue with the plugin, because it is not related. Homebridge plugins only expose the device to HomeKit. Siri is another thing.  Don't sent me details and logs, because I'm not gonna inspect them. I have made this plugin for my needs and sharing it with community, I'm not gonna inspect your problems that are not related with this plugin.

**Comment by ghost** [comment]
> > > This is not related to the homebridge plugin! Although it is working on my setup, so the problem is on your side. Check the naming of your heater device.
> > 
> > 
> > Unfortunately, I left a part out.
> > When Siri is tasked with changing the temperature, it says “OK, heating to 20°C.”. Theres only one heater. Maybe it’s a model issue? Do you want me to send some logs and more details? If it’s not working correctly it’s related to your plugin.
> 
> I can control the heater using Siri. As I said, this can't be issue with the plugin, because it is not related. Homebridge plugins only expose the device to HomeKit. Siri is another thing. Don't sent me details and logs, because I'm not gonna inspect them. I have made this plugin for my needs and sharing it with community, I'm not gonna inspect your problems that are not related with this plugin.

Let me get this straight, Siri doesn’t interact properly with YOUR plugin and your excuse is it works on your side? And it was made for the community? And you are not even gonna explore the issue?
Go back to StackOverflow

**Comment by benov84** [comment]
Let me explain once again, because it seems you're impudent and do not understand nothing. You cannot influence Siri with the plugin. If Home app works, that this is not a plugin problem. You benefit from something that I have made in my free time and shared to the community, and some stupid guy like you is concerned me with his own incompetence! Stop spamming here!
